
services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env

  rag_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.rag_service:app --host 0.0.0.0 --port 8001
    volumes:
      - ./rag_kb:/app/rag_kb
      - ./rag_db:/app/rag_db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - orchestrator