version: '3.8'

services:
  # The Main Orchestrator Service (main.py)
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    # LUCCI'S FIX: This now waits for the RAG service to be fully healthy before starting.
    depends_on:
      rag_service:
        condition: service_healthy

  # The RAG Service (rag_service.py)
  rag_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.rag_service:app --host 0.0.0.0 --port 8001
    volumes:
      - ./rag_kb:/app/rag_kb
      - ./rag_db:/app/rag_db
    # LUCCI'S FIX: This tells Docker how to check if the service is ready.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # Gives the service up to 60s to start up before the first check

  # The Frontend Service (Nginx Web Server)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - orchestrator