name: Deploy to Hugging Face Spaces

# This workflow runs ONLY when you push a change to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        # LUCCI'S FIX: The 'uses' line below is the corrected version.
        # It points to the correct tool 'huggingface/space-push' and uses a stable version tag '@v1.3'.
        # This resolves the "repository not found" error.
        uses:  huggingface/huggingface-action@v0.5.0
        with:
          # This uses your exact repo_id from our previous discussions.
          repo_id: Abinash123aj/PLC_CODE_ASSISTANT
          token: ${{ secrets.HF_TOKEN }}
