name: Deploy to Hugging Face Spaces

# This workflow runs ONLY when you push a change to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        # LUCCI FIX 1: Using a more specific and stable version of the action (v1.3)
        # This resolves the "repository not found" error.
        uses: huggingface/space-push@v1.3
        with:
          # LUCCI FIX 2: Using your exact repo_id from the link you provided
          repo_id: Abinash123aj/PLC_CODE_ASSISTANT
          token: ${{ secrets.HF_TOKEN }}
